export const Cursos = [
  {
    title: "Licenciatura em Libras",
    category: "libras/pedagogia",
    nivel: "graduacao",
    modalidade: "Semi-Presencial",
    duracao: "4 anos",
    thumb: "/cursos/bacharel-letras-libras.png",
    alt: "Licenciatura Letras Libras",
  },
  {
    title: "Bacharelado em Libras",
    category: "libras/pedagogia",
    nivel: "graduacao",
    modalidade: "EAD",
    duracao: "4 anos",
    thumb: "/cursos/Comunicacao-assistiva.png",
    alt: "Bacharelado Letras Libras",
  },
  {
    title: "Pedagogia Bilingue",
    category: "libras/pedagogia",
    nivel: "graduacao",
    modalidade: "EAD",
    duracao: "4 anos",
    thumb: "/cursos/licenciatura-letras-libras.jpg",
    alt: "Pedagogia Bilingue",
  },
  {
    title: "Pedagogia Infantil",
    category: "libras/pedagogia",
    nivel: "graduacao",
    modalidade: "EAD",
    duracao: "4 anos",
    thumb: "/cursos/licenciatura-letras-libras.jpg",
    alt: "Pedagogia Infantil",
  },
  {
    title: "Pedagogia Educação Especial",
    category: "libras/pedagogia",
    nivel: "graduacao",
    modalidade: "EAD",
    duracao: "4 anos",
    thumb: "/cursos/licenciatura-letras-libras.jpg",
    alt: "Pedagogia Educação Especial",
  },

  {
    title: "Pós-graduação em Tradução, Interpretação e/ou Docência da Libras",
    category: "libras",
    nivel: "pos",
    modalidade: "EAD",
    duracao: "12 meses",
    thumb: "/cursos/Pedagogia.png",
    alt: "Pos em Pedagogia",
  },
  {
    title: "Pós-graduação em Libras",
    category: "libras",
    nivel: "pos",
    modalidade: "EAD",
    duracao: "12 meses",
    thumb: "/cursos/Pedagogia-bil.png",
    alt: "Pos em Libras",
  },
  {
    title: "Capacitação em LIBRAS",
    category: "libras",
    nivel: "pos",
    modalidade: "EAD",
    duracao: "64 meses",
    thumb: "/cursos/familia-desenvolvimento-infantil.jpg",
    alt: "familia-desenvolvimento-infantil",
  },
  {
    title: "Pós-Graduação em Educação Bilíngue",
    category: "libras especializado",
    nivel: "pos",
    modalidade: "EAD",
    duracao: "64 meses",
    thumb: "/cursos/familia-desenvolvimento-infantil.jpg",
    alt: "familia-desenvolvimento-infantil",
  },
  {
    title: "Pós-Graduação em Atendimento Educacional Especializado (AEE)",
    category: "especializado",
    nivel: "pos",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/pedagogia educação especial.png",
    alt: "AEE",
  },
  {
    title: "Pós-Graduação em Tradução e Interpretação de Libras em Contextos Religiosos",
    category: "libras",
    nivel: "pos",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/pedagogia educação especial.png",
    alt: "AEE",
  },
  {
    title: "Pós-Graduação em Tradução e Interpretação de Libras em Contextos Midiáticos e Audiovisuais",
    category: "libras",
    nivel: "pos",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/pedagogia educação especial.png",
    alt: "AEE",
  },
  {
    title: "Pós-Graduação em Tradução e Interpretação de Libras em Contextos Jurídicos",
    category: "libras",
    nivel: "pos",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/pedagogia educação especial.png",
    alt: "AEE",
  },
  {
    title: "Pós-Graduação em Tradução e Interpretação de Libras em Contextos Educacionais",
    category: "libras",
    nivel: "pos",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/pedagogia educação especial.png",
    alt: "AEE",
  },
  {
    title: "Pós-Graduação em Autismo (TEA)",
    category: "especializado",
    nivel: "pos",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/pedagogia educação especial.png",
    alt: "AEE",
  },

  {
    title: "TEGEA",
    category: "livres",
    nivel: "livres",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/Pedagogia gestão escolar.png",
    alt: "Pedagogia gestão escolar",
  },
  {
    title: "libras-meetings2020-02.jpg",
    category: "livres",
    nivel: "livres",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/libras-meetings2020-02.jpg",
    alt: "libras-meetings2020-02.jpg",
  },
  {
    title: "libras-premium",
    category: "livres",
    nivel: "livres",
    modalidade: "Online",
    duracao: "5 meses",
    thumb: "/cursos/libras-premium.jpg",
    alt: "libras-premium",
  },
  {
    title: "neurociencia-educacao-2",
    category: "livres",
    nivel: "livres",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/neurociencia-educacao-2.jpg",
    alt: "neurociencia-educacao-2",
  },
  {
    title: "desconto-progressivo-ensino-digital-thumb.png",
    category: "livres",
    nivel: "livres",
    modalidade: "Online",
    duracao: "3 meses",
    thumb: "/cursos/desconto-progressivo-ensino-digital-thumb.png",
    alt: "desconto-progressivo-ensino-digital-thumb.png",
  },

  {
    title: "Análise e Desenvolvimento de Sistemas",
    category: "tecgea",
    nivel: "graduacao",
    duracao: "2 anos",
    modalidade: "EAD",
    thumb: "/cursos/capacitacao@0.3x.png",
    alt: "Análise e Desenvolvimento de Sistemas",
  },
  {
    title: "Gestão de T.I",
    category: "tecgea",
    nivel: "graduacao",
    duracao: "2 anos",
    modalidade: "EAD",
    thumb: "/cursos/LIBRAS-FLUENCY.png",
    alt: "Gestão de T.I",
  },
  {
    title: "Marketing",
    category: "tecgea",
    nivel: "graduacao",
    duracao: "2 anos",
    modalidade: "EAD",
    thumb: "/cursos/libras@0.3x.png",
    alt: "Marketing",
  },
  {
    title: "Processos Gerenciais",
    category: "tecgea",
    nivel: "graduacao",
    duracao: "2 anos",
    modalidade: "EAD",
    thumb: "/cursos/thumb-pos-autismo.jpg",
    alt: "Processos Gerenciais",
  },
  {
    title: "Gestão Financeira",
    category: "tecgea",
    nivel: "graduacao",
    duracao: "2 anos",
    modalidade: "EAD",
    thumb: "/cursos/thumb-pos-libras-expert-EDUCACIONAL.jpg",
    alt: "Gestão Financeira",
  },
  {
    title: "Gestão Comercial",
    category: "tecgea",
    nivel: "graduacao",
    duracao: "2 anos",
    modalidade: "EAD",
    thumb: "/cursos/thumb-pos-libras-expert-JURIDICO.jpg",
    alt: "Gestão Comercial",
  },
];
